remove coordinates from rooms

diff --git a/bin/jump b/bin/jump
--- a/bin/jump
+++ b/bin/jump
@@ -1,23 +1,17 @@
 #!/bin/bash
 
-if [ "$#" = 0 ]; then
-	if load user $USERNAME location; then
-		COORDINATES_RESULT=$($BIN/coordinates "${location[@]}")
-	else
-		COORDINATES_RESULT=$($BIN/coordinates 1 0 1)
-	fi
+if [ "$#" -lt 1 ] || [ -z "$*"]; then
+	echo "No location given"
+	$(exit 1)
+elif [ grep -q '[.*]' <<< $* ]; then
+	echo "Illegal charachters in jump command: $*"
+	$(exit 2)	
+elif ! [ -f "$ROOMS/$*/description" ]; then
+	echo "Room not found"
+	$(exit 3)
 else
-	COORDINATES_RESULT=$($BIN/coordinates "$@")
-fi
-
-if [ ! $? -eq 0 ]; then
-	echo "$COORDINATES_RESULT"
-elif [ -e "$COORDINATES_RESULT" ]; then
-	cd "$COORDINATES_RESULT"
-	read -ra location <<< "$($BIN/location)"
-	save user $USERNAME location
-else
-	echo "Location does not exist"
-	false
-fi
+	cd "$ROOMS/$*"
+	location=$($BIN/location)
+	save user location
+fi 2>/dev/null
 
