add user location

diff --git a/PATHS b/PATHS
--- a/PATHS
+++ b/PATHS
@@ -1,11 +1,68 @@
 #!/bin/bash
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" || exit $?
+
+set -a
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" || exit
 DATA="$DIR/data"
 BIN="$DIR/bin"
 USERS="$DATA/users"
 SETTINGS="$DATA/settings"
 RUNTIME="$DATA/runtime"
 ROOMS="$DATA/rooms"
-PGID=$(ps -o pgid= $$ | grep -o '[0-9]*') || exit $?
+PGID=$(ps -o pgid= $$ | grep -o '[0-9]*') || exit
+
+
+
+function save() {
+	if [ ! "$#" -eq 3 ]; then
+		echo "ERROR: Save expects arguments length 3"
+		return 1
+	fi
+
+
+	if [ "${1,,}" = "user" ]; then
+		basePath="$USERS/$2"
+	else
+		echo "ERROR: Unkown variable owner type $2"
+		return 2
+	fi
+
+
+	if [ ! -d "$basePath" ]; then
+		echo "ERROR: Base directory does not exist $basePath"
+		return 3
+	fi
+
+
+	declare -p $3 > "$basePath/$3"
+}
+
+
+function load() {
+
+	if [ ! "$#" -eq 3 ]; then 
+		echo "ERROR: Load expects arguments length 3"
+		return 1
+	fi
+
+	if [ "${1,,}" = "user" ]; then
+		 path="$USERS/$2/$3"
+	else
+		echo "ERROR: Unkown variable owner type $2"
+		return 2
+	fi
+
+	if [ ! -f "$path" ]; then
+		echo "ERROR: value does not exist $path"
+		return 3
+	fi
+
+
+	source "$path"
+
+}
+
+
+set +a
+
 
